import { UIResourceRenderer } from '@mcp-ui/client'
import type { UIActionResult } from '@mcp-ui/client'
import { useEffect, useMemo, useState } from 'react'
import './App.css'

type LogEntry = {
  ts: string
  action: unknown
}

function App() {
  const [logs, setLogs] = useState<LogEntry[]>([])
  const [resourceOverride, setResourceOverride] = useState<
    | {
        uri?: string
        mimeType?: string
        text?: string
        blob?: string
        _meta?: Record<string, unknown>
      }
    | null
  >(null)
  const [resourceError, setResourceError] = useState<string | null>(null)

  const resource = useMemo(() => {
    // If the bridge is running, it will provide the resource generated by the MCP server.
    if (resourceOverride) return resourceOverride

    // Fallback: hardcoded resource (useful when you only run host+ui).
    return { uri: 'ui://spike/demo/1', mimeType: 'text/uri-list', text: 'http://localhost:5174/' }
  }, [resourceOverride])

  useEffect(() => {
    async function load() {
      try {
        setResourceError(null)
        const res = await fetch('http://localhost:8787/resource')
        if (!res.ok) throw new Error(`Bridge returned HTTP ${res.status}`)
        const json = (await res.json()) as any
        // Bridge returns { type: 'resource', resource: {...} }
        setResourceOverride(json?.resource ?? null)
      } catch (err) {
        // This is expected until you start apps/bridge.
        setResourceError(err instanceof Error ? err.message : String(err))
      }
    }
    load()
  }, [])

  return (
    <>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 420px', gap: 16 }}>
        <div>
          <h2 style={{ marginTop: 0 }}>MCP-UI Spike Host</h2>
          <p style={{ marginTop: 0 }}>
            This React app is the <strong>host</strong>. It renders a UI resource in an iframe and
            handles UI actions.
          </p>
          {resourceError ? (
            <p style={{ marginTop: 0, color: '#ffb86c' }}>
              Bridge not connected yet ({resourceError}). Falling back to a hardcoded resource.
            </p>
          ) : (
            <p style={{ marginTop: 0, opacity: 0.8 }}>Resource loaded from bridge (MCP server).</p>
          )}

          <UIResourceRenderer
            resource={resource}
            htmlProps={{
              autoResizeIframe: true,
              sandboxPermissions: 'allow-forms allow-popups'
            }}
            onUIAction={async (action: UIActionResult) => {
              const entry: LogEntry = { ts: new Date().toISOString(), action }
              setLogs((prev) => [entry, ...prev].slice(0, 50))

              // Translate UI actions into tool calls via the bridge (which talks to the MCP server).
              if (action.type === 'tool') {
                const resp = await fetch('http://localhost:8787/ui-action', {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify(action)
                })
                if (!resp.ok) {
                  return { ok: false, error: `Bridge returned HTTP ${resp.status}` }
                }
                return await resp.json()
              }

              // Non-tool actions are returned as-is for now (spike).
              return { ok: true, receivedAt: entry.ts, ignored: true, action }
            }}
          />
        </div>

        <aside style={{ borderLeft: '1px solid #333', paddingLeft: 16 }}>
          <h3 style={{ marginTop: 0 }}>onUIAction logs</h3>
          <p style={{ marginTop: 0, opacity: 0.8 }}>
            When the iframe posts a message (tool/link/prompt/etc), it shows up here.
          </p>
          <pre
            style={{
              maxHeight: 520,
              overflow: 'auto',
              background: '#0b1020',
              padding: 12,
              borderRadius: 8
            }}
          >
            {logs.length === 0
              ? 'No actions yet. Click the button inside the iframe.'
              : JSON.stringify(logs, null, 2)}
          </pre>
        </aside>
      </div>
    </>
  )
}

export default App
